### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by uier** [Normal-OJ/Normal-OJ#23]
有許多參與貢獻的同學想將 NOJ 的經歷寫在履歷、備審資料，如果能有一個展示用的網站或影片，會比直接貼上 noj.tw 好許多

**Comment by Bogay** [comment]
或許也可以像 [QingdaoU/OnlineJudge](https://github.com/QingdaoU/OnlineJudge) 那樣寫一些關於架構，設計的文件？（例如[這個](https://opensource.qduoj.com/#/judger/how_it_works)）

**Comment by uier** [comment]
https://hackmd.io/@uier/demo-proposal

**Comment by uier** [comment]
未來討論請移至 [@Normal-OJ/.github](https://github.com/Normal-OJ/.github)
