### ISSUE TITLE
讓 CORS 支援 wildcard

### ISSUE THREAD

**Issue by Bogay** [Normal-OJ/Normal-OJ#24]
這樣可以讓前端 review 的時候輕鬆一點，直接用 cloudflare 的 branch preview 來看。
目前是用 caddy 的 `header` 來匹配，或許可以考慮改寫成使用 `header_regexp`（[doc](https://caddyserver.com/docs/caddyfile/matchers#header-regexp)）

**Comment by JacobLinCool** [comment]
我們在 @UniCourse 是使用：

```Caddyfile
@dev header_regexp dev_origin Origin "https://[^.]+\.domain\.pages.dev"
header @dev Access-Control-Allow-Origin {re.dev_origin.0}
```
