### ISSUE TITLE
Add PATCH method in Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by uier** [Normal-OJ/Normal-OJ#34]
Recently we have a new API `PATCH /user/<username>` for NOJ admin to modify users data, but on `noj.tw` the request is blocked by CORS, which is caused by the reason that we did not have PATCH in our Access-Control-Allow-Methods header

https://github.com/Normal-OJ/Normal-OJ/blob/9db1ff8772e0dc8833663e0dad8c3576bbe5d2c6/.config/Caddyfile.prod#L9

**Comment by Bogay** [comment]
Closed by #39
