### ISSUE TITLE
Password management

### ISSUE THREAD

**Issue by uier** [Normal-OJ/Normal-OJ#38]
https://github.com/1Password/1password-teams-open-source

**Comment by uier** [comment]
@as535364 could you please update your recent work of 1password?

**Comment by as535364** [comment]
剩下發 PR 到 [1password-teams-open-source](https://github.com/1Password/1password-teams-open-source/pulls)

**Comment by as535364** [comment]
處理好了，等他 merge，但目前還有其他人過一週還沒被 merge

**Comment by as535364** [comment]
done
